pipeline {
    agent any

    stages {

        stage ('Build Docker Image') {
            steps {
                script {
                    dockerapp = docker.build("taffarel55/kube-news:${env.BUILD_ID}", '-f ./aula5/kube-news/src/Dockerfile ./aula5/kube-news/src')
                }
            }
        }

        stage ('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry("https://registry.hub.docker.com", 'dockerhub') {
                        dockerapp.push('latest')
                        dockerapp.push("${env.BUILD_ID}")
                    }
                }
            }
        }

        stage ('Deploy Kubernetes') {
            environment {
                tag_version = "${env.BUILD_ID}"
            }
            steps {
                script {
                    withKubeConfig([credentialsId: 'kubeconfig']) {
                        sh 'sed -i "s/{{TAG}}/$tag_version/g" ./aula5/kube-news/k8s/deployment.yaml'
                        sh 'kubectl apply -f ./aula5/kube-news/k8s/deployment.yaml'
                    }
                }
                
            }

        }

    }
}