apiVersion: v1
kind: Pod
metadata:
  name: meupod-azul
  labels:
    cor: azul
spec:
  containers:
    - name: site-container
      image: fabricioveronez/web-page:blue
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
---
apiVersion: v1
kind: Pod
metadata:
  name: meupod-verde
  labels:
    cor: verde
spec:
  containers:
    - name: site-container
      image: fabricioveronez/web-page:blue
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"