pipeline {
    agent any

    stages {

        stage ('Build Docker Image') {
            steps {
                script {
                    dockerapp = docker.build("taffarel55/kube-news:${env.BUILD_ID}", '-f ./aula4/kube-news/src/Dockerfile ./aula4/kube-news/src')
                }
            }
        }

        stage ('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry("https://registry.hub.docker.com", 'dockerhub') {
                        dockerapp.push('latest')
                        dockerapp.push("${env.BUILD_ID}")
                    }
                }
            }
        }

        stage ('Deploy Kubernetes') {
            steps {
                script {
                    withKubeconfig([credentialsId: 'kubeconfig']) {
                        sh 'kubectl apply -f ./aula4/kube-news/k8s/deployment.yaml'
                    }
                }
            }

        }

    }
}